version: '3.8'

services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    command: python app.py

  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    command: streamlit run streamlit.py
